version: '3.5'

services:
    documize:
        image: targodan/documize:latest
        restart: always
        ports:
            - "80:80"
        environment:
            - DOCUMIZE_DB_TYPE=mysql
            - DOCUMIZE_DB_CONNECTION="Documize@documize:dbclkr4GAcX6Nsag8wLp@tcp(documize.mysql.database.azure.com:3306)/documize"
